# Generated by Django 4.0.10 on 2024-04-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ycms', '0031_alter_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textcontent',
            name='buttonText',
            field=models.CharField(default='', max_length=120),
        ),
    ]
