# Generated by Django 4.0.10 on 2024-04-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ycms', '0032_alter_textcontent_buttontext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textcontent',
            name='buttonText',
            field=models.CharField(default='', max_length=300),
        ),
    ]
